joint_limits:
  joint1:
    has_position_limits: true
    min_position: 42
    max_position: 260
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: true
    max_effort: 5.0

  joint2:
    has_position_limits: true
    min_position: 42
    max_position: 260
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: true
    max_effort: 5.0  

  joint3:
    has_position_limits: true
    min_position: 42
    max_position: 260
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: true
    max_effort: 5.0

  joint4:
    has_position_limits: true
    min_position: 42
    max_position: 260
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: true
    max_effort: 5.0

  joint5:
    has_position_limits: true
    min_position: -113
    max_position: 113
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: true
    max_effort: 5.0

  # joint6:
  #   has_position_limits: true
  #   min_position: -68
  #   max_position: 157
  #   has_velocity_limits: true
  #   max_velocity: 2.0
  #   has_acceleration_limits: true
  #   max_acceleration: 5.0
  #   has_jerk_limits: true
  #   max_jerk: 100.0
  #   has_effort_limits: true
  #   max_effort: 5.0

  # joint7:
  #   has_position_limits: true
  #   min_position: -150
  #   max_position: 250
  #   has_velocity_limits: true
  #   max_velocity: 2.0
  #   has_acceleration_limits: true
  #   max_acceleration: 5.0
  #   has_jerk_limits: true
  #   max_jerk: 100.0
  #   has_effort_limits: true
  #   max_effort: 5.0
